### ISSUE TITLE
Feature request: Route where options

### ISSUE THREAD

**Issue by DJWassink** [JBlaak/Express-Torch#20]
Currently in express we can add regex to our route to match a certain condition, for example:

```js
router.get('/user/:id(\\d+)');
```

Which will only match if the id is an number, but this makes the routes unreadable, Laravel fixed this issue by defining the constraints in another place, for example:

```php
Route::get('/user/{id}/', [...])->where(['id' => '[0-9]+']);
```

Maybe it would be possible to support something similar? 😅

**Comment by JBlaak** [comment]
Great idea, this would make things quite a bit easier.

I think this is quite easily added, if you look at https://github.com/JBlaak/Express-Torch/blob/master/src/router.ts#L68 for example. There's nothing returned from the `get`, `post`, `put` and `delete` methods. We should, maybe, wrap the route in an object which allows for this pattern and just return it.

**Comment by JBlaak** [comment]
Released in https://github.com/JBlaak/Express-Torch/releases/tag/v0.1.7 closing.
